// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsdbnoghfmqbhihkpuum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzZGJub2doZm1xYmhpaGtwdXVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MjI3MDQsImV4cCI6MjA2MTE5ODcwNH0.MOlsh74XgvhahL7atOwIkZLiBmxfUeuvQ9hb_00j7XA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);